package avatar.constants;
import java.util.HashMap;
import java.util.Map;
public class Cmd {

    public static final byte TRANS_ICON_WEDDING = -103;
    public static final byte CHANS_MONEY_XENG = -102;
    public static final byte ADD_MENU = -101;
    public static final byte CUSTOM_CHEST = -87;
    public static final byte PASS_CHEST = -88;
    public static final byte UPGRADE_CHEST = -90;
    public static final byte CREATE_CHAR_INFO = -106;
    public static final byte SHOP_HOUSE = -107;
    public static final byte SELECTED_FLOWER_LOVE = -106;
    public static final byte FLOWER_LOVE = -105;
    public static final byte JOIN_HOUSE_4 = -104;
    public static final byte JOIN_OFFLINE_MAP = -99;
    public static final byte REQUEST_IMAGE_PART = -98;
    public static final byte REQUEST_DYNAMIC_PART = -97;
    public static final byte JOIN_ONGAME_MINI = -96;
    public static final byte REQUEST_JOIN_ANY = -95;
    public static final byte REQUEST_TILE_MAP = -94;
    public static final byte SELECTED_MINI_MAP = -93;
    public static final byte REQUEST_CITY_MAP = -92;
    public static final byte REQUEST_MONEY_LOAD = -91;
    public static final byte TRANS_PART_CHEST = -89;
    public static final byte EMOTION_LIST = -85;
    public static final byte EFFECT_OBJ = -84;
    public static final byte MENU_ROTATE = -83;
    public static final byte CHANGE_CLAN = -82;
    public static final byte CUSTOM_LIST = -81;
    public static final byte GET_IMG_ICON = -80;
    public static final byte SET_AGENT = -79;
    public static final byte BOSS_SHOP = -78;
    public static final byte CUSTOM_POPUP = -77;
    public static final byte SMS_SERVER_LOAD = -76;
    public static final byte SET_PASS_MY_HOUSE = -75;
    public static final byte BUY_ITEM_HOUSE = -74;
    public static final byte GET_TILE_MAP = -73;
    public static final byte SERVER_KICK = -72;
    public static final byte SORT_ITEM_HOUSE = -71;
    public static final byte REQUEST_EXPICE_PET = -70;
    public static final byte KICK_OUT_HOME = -69;
    public static final byte INVITE_TO_MY_HOME = -68;
    public static final byte GET_TYPE_HOUSE = -67;
    public static final byte DEL_ITEM_HOUSE = -66;
    public static final byte JOIN_HOUSE = -65;
    public static final byte DIAL_LUCKY = -64;
    public static final byte WEATHER = -63;
    public static final byte CHANGE_PASS = -62;
    public static final byte COMMUNICATE = -61;
    public static final byte TEXT_BOX = -60;
    public static final byte MENU_OPTION = -59;
    public static final byte CUSTOM_TAB = -58;
    public static final byte LOAD_CARD = -56;
    public static final byte REQUEST_SERVICE = -55;
    public static final byte SMS = -54;
    public static final byte UPDATE_CONTAINER = -53;
    public static final byte NUMBER_SUPPORT = -52;
    public static final byte SOUND_DATA = -51;
    public static final byte REQUEST_SOUND = -50;
    public static final byte OPEN_SHOP = -49;
    public static final byte USING_PART = -48;
    public static final byte CONTAINER = -47;
    public static final byte CREATE_HOME = -46;
    public static final byte BUY_HOME = -45;
    public static final byte GET_IMG_OBJ_INFO = -43;
    public static final byte MAP_AD = -42;
    public static final byte MAP_ITEM = -41;
    public static final byte MAP_ITEM_TYPE = -40;
    public static final byte PARK_BUY_ITEM = -38;
    public static final byte GET_ITEM_INFO = -37;
    public static final byte REMOVE_ITEM = -36;
    public static final byte CRE_CHARACTER = -35;
    public static final byte UPDATE_MONEY = -33;
    public static final byte REQUEST_REGISTER = -30;
    public static final byte UPDATE_USERDATA = -29;
    public static final byte USER_DATA = -28;
    public static final byte REGISTER_BY_EMAIL = -25;
    public static final byte AVATAR_BUY_ITEM = -24;
    public static final byte REQUEST_CHARGE_MONEY_INFO = -23;
    public static final byte REQUEST_YOUR_INFO = -22;
    public static final byte AVATAR_REQUEST_ADD_FRIEND = -21;
    public static final byte REMOVE_FRIEND = -20;
    public static final byte ADD_FRIEND = -19;
    public static final byte REQUEST_FRIENDLIST = -18;
    public static final byte SET_PROVIDER = -17;
    public static final byte GET_AVATAR_PART = -16;
    public static final byte GET_IMAGE = -15;
    public static final byte GET_BIG = -14;
    public static final byte LOGIN_NEW_GAME = -12;
    public static final byte SET_BIG = -11;
    public static final byte SET_MONEY_ERROR = -10;
    public static final byte SERVER_MESSAGE = -9;
    public static final byte SERVER_INFO = -8;
    public static final byte VERSION = -7;
    public static final byte CHAT_TO = -6;
    public static final byte LOGIN_FAIL = -5;
    public static final byte LOGIN_SUCESS = -4;
    public static final byte LOGIN = -2;
    public static final byte GET_HANDLER = -1;
    public static final byte DAT_CUOC = 5;
    public static final byte JOIN_ROOM_RACE = 1;
    public static final byte PET_INFO = 2;
    public static final byte HISTORY_PET_RACE = 8;
    public static final byte JOIN_BOARD = 8;
    public static final byte CHAT_TO_BOARD = 9;
    public static final byte WINER_INFO = 10;
    public static final byte ROOM_NAME = 0;
    public static final byte REQUEST_ROOMLIST = 6;
    public static final byte REQUEST_BOARDLIST = 7;
    public static final byte KICK = 11;
    public static final byte SOMEONE_JOINBOARD = 12;
    public static final byte SOMEONE_LEAVEBOARD = 14;
    public static final byte LEAVE_BOARD = 15;
    public static final byte READY = 16;
    public static final byte SET_PASS = 18;
    public static final byte SET_MONEY = 19;
    public static final byte START = 20;
    public static final byte MOVE_CARO = 21;
    public static final byte MOVE_TIENLEN = 21;
    public static final byte TO_XONG = 21;
    public static final byte MOVE_AND_WIN_CARO = 22;
    public static final byte FORCE_LOSE = 23;
    public static final byte DRAW = 25;
    public static final byte JOIN_ANY_BOARD = 28;
    public static final byte STRONGEST_LIST = 30;
    public static final byte RICHEST_lIST = 31;
    public static final byte REQUEST_DETAIL = 34;
    public static final byte SEARCH = 36;
    public static final byte GAME_RESULT = 37;
    public static final byte REQUEST_AVATAR = 38;
    public static final byte REQUEST_AVATARLIST = 39;
    public static final byte STOP_GAME = 50;
    public static final byte FINISH = 51;
    public static final byte BONUS_MONEY = 52;
    public static final byte FORCE_FINISH = 53;
    public static final byte MOVE_ERROR = 54;
    public static final byte SET_MAX_PLAYER = 56;
    public static final byte SEND_SMS_FINISH = 57;
    public static final byte SKIP_TIENLEN = 49;
    public static final byte UP_BO = 49;
    public static final byte CHIA_BAI = 59;
    public static final byte WIN = 60;
    public static final byte PLAYING = 62;
    public static final byte SET_GAME_TYPE = 61;
    public static final byte GET_CARD = 63;
    public static final byte EAT_CARD = 64;
    public static final byte HA_PHOM = 65;
    public static final byte ADD_CARD = 67;
    public static final byte RESET_PHOM_EAT = 68;
    public static final byte DEN_BAI = 69;
    public static final byte ONCE_WIN = 70;
    public static final byte AVATAR_JOIN_PARK = 50;
    public static final byte PLAYER_JOIN_PARK = 51;
    public static final byte PLAYER_LEAVE_PARK = 53;
    public static final byte MOVE_PARK = 54;
    public static final byte CHAT_PARK = 55;
    public static final byte AVATAR_CHAT_PRIVATE = 56;
    public static final byte AVATAR_FEEL = 57;
    public static final byte AVATAR_GIFT_GIVING = 58;
    public static final byte ACTION = 59;
    public static final byte PARK_BOARD_LIST = 60;
    public static final byte PARK_KICK = 78;
    public static final byte KICH = 67;
    public static final byte DATA_DIAMOND = 71;
    public static final byte ADMIN_COMMAND = 75;
    public static final byte DROP_FISH = 79;
    public static final byte BITE_FISH = 80;
    public static final byte FINISH_FISH = 81;
    public static final byte QUANG_CAU = 82;
    public static final byte CA_CAN_CAU = 83;
    public static final byte CAU_THANH_CONG = 84;
    public static final byte CAU_CA_XONG = 85;
    public static final byte START_CAU_CA = 86;
    public static final byte STATUS_FISH = 87;
    public static final byte INFO_FISH = 88;
    public static final byte SET_BIG_FARM = 51;
    public static final byte GET_BIG_FARM = 54;
    public static final byte GET_IMAGE_FARM = 55;
    public static final byte GET_TREE_INFO = 56;
    public static final byte INVENTORY = 60;
    public static final byte JOIN = 61;
    public static final byte BUY_ITEM = 62;
    public static final byte SELL_ITEM = 63;
    public static final byte PLANT_SEED = 64;
    public static final byte USING_ITEM = 65;
    public static final byte TREE_HARVEST = 66;
    public static final byte REQUEST_SLOT = 69;
    public static final byte OPEN_LAND = 70;
    public static final byte BUY_ANIMAL = 71;
    public static final byte PRICE_ANIMAL = 72;
    public static final byte SELL_ANIMAL = 73;
    public static final byte HARVEST_ANIMAL = 74;
    public static final byte TRANSFER_MONEY = 75;
    public static final byte MOVE_FARM = 76;
    public static final byte CHAT_FARM = 77;
    public static final byte INFO_CELL = 78;
    public static final byte INFO_ANIMAL = 79;
    public static final byte DROP_PART = 89;
    public static final byte CAN_CAU = 91;
    public static final byte SET_TURN = 100;
    public static final byte OUT_PATH = 24;
    public static final byte UPDATE_FARM_CATTLE = 80;
    public static final byte UPDATE_FARM_FISH = 81;
    public static final byte GET_IMG_FARM = 82;
    public static final byte UPDATE_STARFRUIL = 84;
    public static final byte HARVEST_STARFRUIT = 85;
    public static final byte UPDATE_STARTFRUIT_BYMONEY = 86;
    public static final byte UPDATE_LAND = 90;
    public static final byte COOKING = 91;
    public static final byte FLY = 92;
    public static final byte NAU_NHANH = 93;
    public static final byte HARVEST_COOK = 92;
    public static final byte FINISH_STARFRUIT = 83;
    public static final byte UPDATE_STORE = 94;
    public static final byte GET_INFO_STARFRUIT = 87;
    public static final byte WEDDING_BIGIN = 93;
    public static final byte STEAL_INFO = 95;
    public static final byte STEAL = 96;
    public static final byte STEAL_STORE = 97;
    public static final byte LICH_SU_BI_TROM = 98;
    public static final byte DICH_CHUYEN = 122;
    ////hashMap cmdcode
    public static final Map<Byte, String> CmdCode = new HashMap<Byte, String>() {{
        put((byte) -103, "TRANS_ICON_WEDDING");
        put((byte) -102, "CHANS_MONEY_XENG");
        put((byte) -101, "ADD_MENU");
        put((byte) -87, "CUSTOM_CHEST");
        put((byte) -88, "PASS_CHEST");
        put((byte) -90, "UPGRADE_CHEST");
        put((byte) -106, "CREATE_CHAR_INFO");
        put((byte) -107, "SHOP_HOUSE");
        put((byte) -106, "SELECTED_FLOWER_LOVE");
        put((byte) -105, "FLOWER_LOVE");
        put((byte) -104, "JOIN_HOUSE_4");
        put((byte) -99, "JOIN_OFFLINE_MAP");
        put((byte) -98, "REQUEST_IMAGE_PART");
        put((byte) -97, "REQUEST_DYNAMIC_PART");
        put((byte) -96, "JOIN_ONGAME_MINI");
        put((byte) -95, "REQUEST_JOIN_ANY");
        put((byte) -94, "REQUEST_TILE_MAP");
        put((byte) -93, "SELECTED_MINI_MAP");
        put((byte) -92, "REQUEST_CITY_MAP");
        put((byte) -91, "REQUEST_MONEY_LOAD");
        put((byte) -89, "TRANS_PART_CHEST");
        put((byte) -85, "EMOTION_LIST");
        put((byte) -84, "EFFECT_OBJ");
        put((byte) -83, "MENU_ROTATE");
        put((byte) -82, "CHANGE_CLAN");
        put((byte) -81, "CUSTOM_LIST");
        put((byte) -80, "GET_IMG_ICON");
        put((byte) -79, "SET_AGENT");
        put((byte) -78, "BOSS_SHOP");
        put((byte) -77, "CUSTOM_POPUP");
        put((byte) -76, "SMS_SERVER_LOAD");
        put((byte) -75, "SET_PASS_MY_HOUSE");
        put((byte) -74, "BUY_ITEM_HOUSE");
        put((byte) -73, "GET_TILE_MAP");
        put((byte) -72, "SERVER_KICK");
        put((byte) -71, "SORT_ITEM_HOUSE");
        put((byte) -70, "REQUEST_EXPICE_PET");
        put((byte) -69, "KICK_OUT_HOME");
        put((byte) -68, "INVITE_TO_MY_HOME");
        put((byte) -67, "GET_TYPE_HOUSE");
        put((byte) -66, "DEL_ITEM_HOUSE");
        put((byte) -65, "JOIN_HOUSE");
        put((byte) -64, "DIAL_LUCKY");
        put((byte) -63, "WEATHER");
        put((byte) -62, "CHANGE_PASS");
        put((byte) -61, "COMMUNICATE");
        put((byte) -60, "TEXT_BOX");
        put((byte) -59, "MENU_OPTION");
        put((byte) -58, "CUSTOM_TAB");
        put((byte) -56, "LOAD_CARD");
        put((byte) -55, "REQUEST_SERVICE");
        put((byte) -54, "SMS");
        put((byte) -53, "UPDATE_CONTAINER");
        put((byte) -52, "NUMBER_SUPPORT");
        put((byte) -51, "SOUND_DATA");
        put((byte) -50, "REQUEST_SOUND");
        put((byte) -49, "OPEN_SHOP");
        put((byte) -48, "USING_PART");
        put((byte) -47, "CONTAINER");
        put((byte) -46, "CREATE_HOME");
        put((byte) -45, "BUY_HOME");
        put((byte) -43, "GET_IMG_OBJ_INFO");
        put((byte) -42, "MAP_AD");
        put((byte) -41, "MAP_ITEM");
        put((byte) -40, "MAP_ITEM_TYPE");
        put((byte) -38, "PARK_BUY_ITEM");
        put((byte) -37, "GET_ITEM_INFO");
        put((byte) -36, "REMOVE_ITEM");
        put((byte) -35, "CRE_CHARACTER");
        put((byte) -33, "UPDATE_MONEY");
        put((byte) -30, "REQUEST_REGISTER");
        put((byte) -29, "UPDATE_USERDATA");
        put((byte) -28, "USER_DATA");
        put((byte) -25, "REGISTER_BY_EMAIL");
        put((byte) -24, "AVATAR_BUY_ITEM");
        put((byte) -23, "REQUEST_CHARGE_MONEY_INFO");
        put((byte) -22, "REQUEST_YOUR_INFO");
        put((byte) -21, "AVATAR_REQUEST_ADD_FRIEND");
        put((byte) -20, "REMOVE_FRIEND");
        put((byte) -19, "ADD_FRIEND");
        put((byte) -18, "REQUEST_FRIENDLIST");
        put((byte) -17, "SET_PROVIDER");
        put((byte) -16, "GET_AVATAR_PART");
        put((byte) -15, "GET_IMAGE");
        put((byte) -14, "GET_BIG");
        put((byte) -12, "LOGIN_NEW_GAME");
        put((byte) -11, "SET_BIG");
        put((byte) -10, "SET_MONEY_ERROR");
        put((byte) -9, "SERVER_MESSAGE");
        put((byte) -8, "SERVER_INFO");
        put((byte) -7, "VERSION");
        put((byte) -6, "CHAT_TO");
        put((byte) -5, "LOGIN_FAIL");
        put((byte) -4, "LOGIN_SUCESS");
        put((byte) -2, "LOGIN");
        put((byte) -1, "GET_HANDLER");
        put((byte) 5, "DAT_CUOC");
        put((byte) 1, "JOIN_ROOM_RACE");
        put((byte) 2, "PET_INFO");
        put((byte) 8, "HISTORY_PET_RACE");
        put((byte) 8, "JOIN_BOARD");
        put((byte) 9, "CHAT_TO_BOARD");
        put((byte) 10, "WINER_INFO");
        put((byte) 0, "ROOM_NAME");
        put((byte) 6, "REQUEST_ROOMLIST");
        put((byte) 7, "REQUEST_BOARDLIST");
        put((byte) 11, "KICK");
        put((byte) 12, "SOMEONE_JOINBOARD");
        put((byte) 14, "SOMEONE_LEAVEBOARD");
        put((byte) 15, "LEAVE_BOARD");
        put((byte) 16, "READY");
        put((byte) 18, "SET_PASS");
        put((byte) 19, "SET_MONEY");
        put((byte) 20, "START");
        put((byte) 21, "MOVE_CARO");
        put((byte) 21, "MOVE_TIENLEN");
        put((byte) 21, "TO_XONG");
        put((byte) 22, "MOVE_AND_WIN_CARO");
        put((byte) 23, "FORCE_LOSE");
        put((byte) 25, "DRAW");
        put((byte) 28, "JOIN_ANY_BOARD");
        put((byte) 30, "STRONGEST_LIST");
        put((byte) 31, "RICHEST_lIST");
        put((byte) 34, "REQUEST_DETAIL");
        put((byte) 36, "SEARCH");
        put((byte) 37, "GAME_RESULT");
        put((byte) 38, "REQUEST_AVATAR");
        put((byte) 39, "REQUEST_AVATARLIST");
        put((byte) 50, "STOP_GAME");
        put((byte) 51, "FINISH");
        put((byte) 52, "BONUS_MONEY");
        put((byte) 53, "FORCE_FINISH");
        put((byte) 54, "MOVE_ERROR");
        put((byte) 56, "SET_MAX_PLAYER");
        put((byte) 57, "SEND_SMS_FINISH");
        put((byte) 49, "SKIP_TIENLEN");
        put((byte) 49, "UP_BO");
        put((byte) 59, "CHIA_BAI");
        put((byte) 60, "WIN");
        put((byte) 62, "PLAYING");
        put((byte) 61, "SET_GAME_TYPE");
        put((byte) 63, "GET_CARD");
        put((byte) 64, "EAT_CARD");
        put((byte) 65, "HA_PHOM");
        put((byte) 67, "ADD_CARD");
        put((byte) 68, "RESET_PHOM_EAT");
        put((byte) 69, "DEN_BAI");
        put((byte) 70, "ONCE_WIN");
        put((byte) 50, "AVATAR_JOIN_PARK");
        put((byte) 51, "PLAYER_JOIN_PARK");
        put((byte) 53, "PLAYER_LEAVE_PARK");
        put((byte) 54, "MOVE_PARK");
        put((byte) 55, "CHAT_PARK");
        put((byte) 56, "AVATAR_CHAT_PRIVATE");
        put((byte) 57, "AVATAR_FEEL");
        put((byte) 58, "AVATAR_GIFT_GIVING");
        put((byte) 59, "ACTION");
        put((byte) 60, "PARK_BOARD_LIST");
        put((byte) 78, "PARK_KICK");
        put((byte) 67, "KICH");
        put((byte) 71, "DATA_DIAMOND");
        put((byte) 75, "ADMIN_COMMAND");
        put((byte) 79, "DROP_FISH");
        put((byte) 80, "BITE_FISH");
        put((byte) 81, "FINISH_FISH");
        put((byte) 82, "QUANG_CAU");
        put((byte) 83, "CA_CAN_CAU");
        put((byte) 84, "CAU_THANH_CONG");
        put((byte) 85, "CAU_CA_XONG");
        put((byte) 86, "START_CAU_CA");
        put((byte) 87, "STATUS_FISH");
        put((byte) 88, "INFO_FISH");
        put((byte) 51, "SET_BIG_FARM");
        put((byte) 54, "GET_BIG_FARM");
        put((byte) 55, "GET_IMAGE_FARM");
        put((byte) 56, "GET_TREE_INFO");
        put((byte) 60, "INVENTORY");
        put((byte) 61, "JOIN");
        put((byte) 62, "BUY_ITEM");
        put((byte) 63, "SELL_ITEM");
        put((byte) 64, "PLANT_SEED");
        put((byte) 65, "USING_ITEM");
        put((byte) 66, "TREE_HARVEST");
        put((byte) 69, "REQUEST_SLOT");
        put((byte) 70, "OPEN_LAND");
        put((byte) 71, "BUY_ANIMAL");
        put((byte) 72, "PRICE_ANIMAL");
        put((byte) 73, "SELL_ANIMAL");
        put((byte) 74, "HARVEST_ANIMAL");
        put((byte) 75, "TRANSFER_MONEY");
        put((byte) 76, "MOVE_FARM");
        put((byte) 77, "CHAT_FARM");
        put((byte) 78, "INFO_CELL");
        put((byte) 79, "INFO_ANIMAL");
        put((byte) 89, "DROP_PART");
        put((byte) 91, "CAN_CAU");
        put((byte) 100, "SET_TURN");
        put((byte) 24, "OUT_PATH");
        put((byte) 80, "UPDATE_FARM_CATTLE");
        put((byte) 81, "UPDATE_FARM_FISH");
        put((byte) 82, "GET_IMG_FARM");
        put((byte) 84, "UPDATE_STARFRUIL");
        put((byte) 85, "HARVEST_STARFRUIT");
        put((byte) 86, "UPDATE_STARTFRUIT_BYMONEY");
        put((byte) 90, "UPDATE_LAND");
        put((byte) 91, "COOKING");
        put((byte) 92, "FLY");
        put((byte) 93, "NAU_NHANH");
        put((byte) 92, "HARVEST_COOK");
        put((byte) 83, "FINISH_STARFRUIT");
        put((byte) 94, "UPDATE_STORE");
        put((byte) 87, "GET_INFO_STARFRUIT");
        put((byte) 93, "WEDDING_BIGIN");
        put((byte) 95, "STEAL_INFO");
        put((byte) 96, "STEAL");
        put((byte) 97, "STEAL_STORE");
        put((byte) 98, "LICH_SU_BI_TROM");
        put((byte) 122, "DICH_CHUYEN");
    }};
}
